### PR TITLE
feat: warning icon

### PR DESCRIPTION
**Pull request by kerryambt**
image

Adding Warning icon.

### CODE REVIEW

**Comment by thomasdigby** [comment]
@kerryambt This is already available as `Danger` https://design.atomlearning.technology/theme/icons

**Comment by kerryambt** [comment]
@thomasdigby apparently I'm blind ._. I did look first but oh well. sorry - I'll close now :)

**Comment by thomasdigby** [comment]
> @thomasdigby apparently I'm blind ._. I did look first but oh well. sorry - I'll close now :)

We need a better search for the icons page, that's the main issue, it's just not very good at the moment.

**Comment by kerryambt** [comment]
yeah maybe some kind of tags system that we apply to icons? also maybe getting design to use the same names we do in figma.

**Pull request closed without merging**
