### PR TITLE
feat: add custom icons

### PR DESCRIPTION
**Pull request by taniya-atomlearning**
Added 3 new custom icons: Play & Stop

I initially the viewBox to `viewBox="0 0 24 24"` and removed height and width as per readme, but that cropped the image, so I reverted to the original size

Screenshot 2024-01-24 at 16 38 29

play
stop

### CODE REVIEW

**Comment by thomasdigby** [comment]
As there's already a `PauseCircle` icon, I wonder if each of these should be "circle" icons. e.g. `PlayCircle`, `PauseCircle`, `StopCircle`?

**Comment by taniya-atomlearning** [comment]
> As there's already a `PauseCircle` icon, I wonder if each of these should be "circle" icons. e.g. `PlayCircle`, `PauseCircle`, `StopCircle`?

sure, happy to rename

**Review by LimeWub — APPROVED** [review]

**Comment by thomasdigby** [comment]
Oh sorry, I didn't mean for you to remove your new pause icon. Or is it the same as the current pausecircle icon?

**Comment by taniya-atomlearning** [comment]
> Oh sorry, I didn't mean for you to remove your new pause icon. Or is it the same as the current pausecircle icon?

Looks like there's already a pause icon so just added the play and stop. It says in the ticket it might be the case
https://atomlearningltd.atlassian.net/browse/B2B-539

Screenshot 2024-01-24 at 17 13 10

**Pull request merged**
